### ISSUE TITLE
Cannot import node

### ISSUE THREAD

**Issue by HydraBucket** [cozymantis/human-parser-comfyui-node#10]
Hi, after hours of trying, I can't seem to get this node working. I am using comfy through stability matrix but have tried launching through administration console in VSC. I have downloaded the dependencies into the correct destination within the correct enviornment - im not sure what to do? Any help would be much appreciated. 

** ComfyUI startup time: 2024-05-02 15:29:35.250138
** Platform: Windows
** Python version: 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
** Python executable: E:\AI_Advantage\Data\Packages\Shirt_Swapper\venv\Scripts\python.exe
** Log path: E:\AI_Advantage\Data\Packages\Shirt_Swapper\comfyui.log

Prestartup times for custom nodes:
   0.0 seconds: E:\AI_Advantage\Data\Packages\Shirt_Swapper\custom_nodes\rgthree-comfy
   0.1 seconds: E:\AI_Advantage\Data\Packages\Shirt_Swapper\custom_nodes\ComfyUI-Manager

Total VRAM 24564 MB, total RAM 65244 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync
VAE dtype: torch.bfloat16
Using pytorch cross attention
Adding extra search path checkpoints E:\AI_Advantage\Data\Models\StableDiffusion
Adding extra search path vae E:\AI_Advantage\Data\Models\VAE
Adding extra search path loras E:\AI_Advantage\Data\Models\Lora
Adding extra search path loras E:\AI_Advantage\Data\Models\LyCORIS
Adding extra search path upscale_models E:\AI_Advantage\Data\Models\ESRGAN
Adding extra search path upscale_models E:\AI_Advantage\Data\Models\RealESRGAN
Adding extra search path upscale_models E:\AI_Advantage\Data\Models\SwinIR
Adding extra search path embeddings E:\AI_Advantage\Data\Models\TextualInversion
Adding extra search path hypernetworks E:\AI_Advantage\Data\Models\Hypernetwork
Adding extra search path controlnet E:\AI_Advantage\Data\Models\ControlNet
Adding extra search path controlnet E:\AI_Advantage\Data\Models\T2IAdapter
Adding extra search path clip E:\AI_Advantage\Data\Models\CLIP
Adding extra search path clip_vision E:\AI_Advantage\Data\Models\InvokeClipVision
Adding extra search path diffusers E:\AI_Advantage\Data\Models\Diffusers
Adding extra search path gligen E:\AI_Advantage\Data\Models\GLIGEN
Adding extra search path vae_approx E:\AI_Advantage\Data\Models\ApproxVAE
Adding extra search path ipadapter E:\AI_Advantage\Data\Models\IpAdapter
Adding extra search path ipadapter E:\AI_Advantage\Data\Models\InvokeIpAdapters15
Adding extra search path ipadapter E:\AI_Advantage\Data\Models\InvokeIpAdaptersXl
Adding extra search path prompt_expansion E:\AI_Advantage\Data\Models\PromptExpansion
### Loading: ComfyUI-Impact-Pack (Subpack: V0.5)
[Impact Pack] Wildcards loading done.
### ComfyUI Revision: 2155 [f81a6fad] | Released on '2024-05-01'
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
E:\AI_Advantage\Data\Packages\Shirt_Swapper\venv\lib\site-packages\torch\utils\cpp_extension.py:1967: UserWarning: TORCH_CUDA_ARCH_LIST is not set, all archs for visible cards are included for compilation. 
If this is not desired, please set os.environ['TORCH_CUDA_ARCH_LIST'].
  warnings.warn(
Traceback (most recent call last):
  File "E:\AI_Advantage\Data\Packages\Shirt_Swapper\venv\lib\site-packages\torch\utils\cpp_extension.py", line 2107, in _run_ninja_build
    subprocess.run(
  File "subprocess.py", line 526, in run
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\AI_Advantage\Data\Packages\Shirt_Swapper\nodes.py", line 1864, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\AI_Advantage\Data\Packages\Shirt_Swapper\custom_nodes\human-parser-comfyui-node\__init__.py", line 1, in <module>
    from .HumanParserLIPCustomNode import HumanParserLIPCustomNode
  File "E:\AI_Advantage\Data\Packages\Shirt_Swapper\custom_nodes\human-parser-comfyui-node\HumanParserLIPCustomNode.py", line 5, in <module>
    from .utils import generate
  File "E:\AI_Advantage\Data\Packages\Shirt_Swapper\custom_nodes\human-parser-comfyui-node\utils.py", line 8, in <module>
    from .schp import networks
  File "E:\AI_Advantage\Data\Packages\Shirt_Swapper\custom_nodes\human-parser-comfyui-node\schp\networks\__init__.py", line 3, in <module>
    from .AugmentCE2P import resnet101
  File "E:\AI_Advantage\Data\Packages\Shirt_Swapper\custom_nodes\human-parser-comfyui-node\schp\networks\AugmentCE2P.py", line 21, in <module>
    from ..modules import InPlaceABNSync
  File "E:\AI_Advantage\Data\Packages\Shirt_Swapper\custom_nodes\human-parser-comfyui-node\schp\modules\__init__.py", line 1, in <module>
    from .bn import ABN, InPlaceABN, InPlaceABNSync
  File "E:\AI_Advantage\Data\Packages\Shirt_Swapper\custom_nodes\human-parser-comfyui-node\schp\modules\bn.py", line 10, in <module>
    from .functions import *
  File "E:\AI_Advantage\Data\Packages\Shirt_Swapper\custom_nodes\human-parser-comfyui-node\schp\modules\functions.py", line 12, in <module>
    _backend = load(name="inplace_abn",
  File "E:\AI_Advantage\Data\Packages\Shirt_Swapper\venv\lib\site-packages\torch\utils\cpp_extension.py", line 1309, in load
    return _jit_compile(
  File "E:\AI_Advantage\Data\Packages\Shirt_Swapper\venv\lib\site-packages\torch\utils\cpp_extension.py", line 1719, in _jit_compile
    _write_ninja_file_and_build_library(
  File "E:\AI_Advantage\Data\Packages\Shirt_Swapper\venv\lib\site-packages\torch\utils\cpp_extension.py", line 1832, in _write_ninja_file_and_build_library
    _run_ninja_build(
  File "E:\AI_Advantage\Data\Packages\Shirt_Swapper\venv\lib\site-packages\torch\utils\cpp_extension.py", line 2123, in _run_ninja_build
    raise RuntimeError(message) from e

cl /showIncludes -DTORCH_EXTENSION_NAME=inplace_abn -DTORCH_API_INCLUDE_EXTENSION_H -IE:\AI_Advantage\Data\Packages\Shirt_Swapper\venv\lib\site-packages\torch\include -IE:\AI_Advantage\Data\Packages\Shirt_Swapper\venv\lib\site-packages\torch\include\torch\csrc\api\include -IE:\AI_Advantage\Data\Packages\Shirt_Swapper\venv\lib\site-packages\torch\include\TH -IE:\AI_Advantage\Data\Packages\Shirt_Swapper\venv\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\include" -IE:\AI_Advantage\Data\Packages\Shirt_Swapper\venv\Scripts\Include -D_GLIBCXX_USE_CXX11_ABI=0 /MD /wd4819 /wd4251 /wd4244 /wd4267 /wd4275 /wd4018 /wd4190 /wd4624 /wd4067 /wd4068 /EHsc /std:c++17 -O3 -c E:\AI_Advantage\Data\Packages\Shirt_Swapper\custom_nodes\human-parser-comfyui-node\schp\modules\src\inplace_abn.cpp /Foinplace_abn.o 
Microsoft (R) C/C++ Optimizing Compiler Version 19.39.33523 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

cl : Command line warning D9002 : ignoring unknown option '-O3'

cl /showIncludes -DTORCH_EXTENSION_NAME=inplace_abn -DTORCH_API_INCLUDE_EXTENSION_H -IE:\AI_Advantage\Data\Packages\Shirt_Swapper\venv\lib\site-packages\torch\include -IE:\AI_Advantage\Data\Packages\Shirt_Swapper\venv\lib\site-packages\torch\include\torch\csrc\api\include -IE:\AI_Advantage\Data\Packages\Shirt_Swapper\venv\lib\site-packages\torch\include\TH -IE:\AI_Advantage\Data\Packages\Shirt_Swapper\venv\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\include" -IE:\AI_Advantage\Data\Packages\Shirt_Swapper\venv\Scripts\Include -D_GLIBCXX_USE_CXX11_ABI=0 /MD /wd4819 /wd4251 /wd4244 /wd4267 /wd4275 /wd4018 /wd4190 /wd4624 /wd4067 /wd4068 /EHsc /std:c++17 -O3 -c E:\AI_Advantage\Data\Packages\Shirt_Swapper\custom_nodes\human-parser-comfyui-node\schp\modules\src\inplace_abn.cpp /Foinplace_abn.o 
Microsoft (R) C/C++ Optimizing Compiler Version 19.39.33523 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

cl : Command line warning D9002 : ignoring unknown option '-O3'

E:\AI_Advantage\Data\Packages\Shirt_Swapper\venv\lib\site-packages\diffusers\models\unet_2d_blocks.py:249: FutureWarning: `AutoencoderTinyBlock` is deprecated and will be removed in version 0.29. Importing `AutoencoderTinyBlock` from `diffusers.models.unet_2d_blocks` is deprecated and this will be removed in a future version. Please use `from diffusers.models.unets.unet_2d_blocks import AutoencoderTinyBlock`, instead.
  deprecate("AutoencoderTinyBlock", "0.29", deprecation_message)
E:\AI_Advantage\Data\Packages\Shirt_Swapper\venv\lib\site-packages\diffusers\models\unet_2d_blocks.py:254: FutureWarning: `UNetMidBlock2D` is deprecated and will be removed in version 0.29. Importing `UNetMidBlock2D` from `diffusers.models.unet_2d_blocks` is deprecated and this will be removed in a future version. Please use `from diffusers.models.unets.unet_2d_blocks import UNetMidBlock2D`, instead.
  deprecate("UNetMidBlock2D", "0.29", deprecation_message)
E:\AI_Advantage\Data\Packages\Shirt_Swapper\venv\lib\site-packages\diffusers\models\unet_2d_blocks.py:259: FutureWarning: `UNetMidBlock2DCrossAttn` is deprecated and will be removed in version 0.29. Importing `UNetMidBlock2DCrossAttn` from `diffusers.models.unet_2d_blocks` is deprecated and this will be removed in a future version. Please use `from diffusers.models.unets.unet_2d_blocks import UNetMidBlock2DCrossAttn`, instead.
  deprecate("UNetMidBlock2DCrossAttn", "0.29", deprecation_message)
E:\AI_Advantage\Data\Packages\Shirt_Swapper\venv\lib\site-packages\diffusers\models\unet_2d_blocks.py:264: FutureWarning: `UNetMidBlock2DSimpleCrossAttn` is deprecated and will be removed in version 0.29. Importing `UNetMidBlock2DSimpleCrossAttn` from `diffusers.models.unet_2d_blocks` is deprecated and this will be removed in a future version. Please use `from diffusers.models.unets.unet_2d_blocks import UNetMidBlock2DSimpleCrossAttn`, instead.
  deprecate("UNetMidBlock2DSimpleCrossAttn", "0.29", deprecation_message)
E:\AI_Advantage\Data\Packages\Shirt_Swapper\venv\lib\site-packages\diffusers\models\unet_2d_blocks.py:269: FutureWarning: `AttnDownBlock2D` is deprecated and will be removed in version 0.29. Importing `AttnDownBlock2D` from `diffusers.models.unet_2d_blocks` is deprecated and this will be removed in a future version. Please use `from diffusers.models.unets.unet_2d_blocks import AttnDownBlock2D`, instead.
  deprecate("AttnDownBlock2D", "0.29", deprecation_message)
E:\AI_Advantage\Data\Packages\Shirt_Swapper\venv\lib\site-packages\diffusers\models\unet_2d_blocks.py:274: FutureWarning: `CrossAttnDownBlock2D` is deprecated and will be removed in version 0.29. Importing `AttnDownBlock2D` from `diffusers.models.unet_2d_blocks` is deprecated and this will be removed in a future version. Please use `from diffusers.models.unets.unet_2d_blocks import CrossAttnDownBlock2D`, instead.
  deprecate("CrossAttnDownBlock2D", "0.29", deprecation_message)
E:\AI_Advantage\Data\Packages\Shirt_Swapper\venv\lib\site-packages\diffusers\models\unet_2d_blocks.py:279: FutureWarning: `DownBlock2D` is deprecated and will be removed in version 0.29. Importing `DownBlock2D` from `diffusers.models.unet_2d_blocks` is deprecated and this will be removed in a future version. Please use `from diffusers.models.unets.unet_2d_blocks import DownBlock2D`, instead.
  deprecate("DownBlock2D", "0.29", deprecation_message)
E:\AI_Advantage\Data\Packages\Shirt_Swapper\venv\lib\site-packages\diffusers\models\unet_2d_blocks.py:284: FutureWarning: `AttnDownEncoderBlock2D` is deprecated and will be removed in version 0.29. Importing `AttnDownEncoderBlock2D` from `diffusers.models.unet_2d_blocks` is deprecated and this will be removed in a future version. Please use `from diffusers.models.unets.unet_2d_blocks import AttnDownEncoderBlock2D`, instead.
  deprecate("AttnDownEncoderBlock2D", "0.29", deprecation_message)
E:\AI_Advantage\Data\Packages\Shirt_Swapper\venv\lib\site-packages\diffusers\models\unet_2d_blocks.py:289: FutureWarning: `AttnSkipDownBlock2D` is deprecated and will be removed in version 0.29. Importing `AttnSkipDownBlock2D` from `diffusers.models.unet_2d_blocks` is deprecated and this will be removed in a future version. Please use `from diffusers.models.unets.unet_2d_blocks import AttnSkipDownBlock2D`, instead.
  deprecate("AttnSkipDownBlock2D", "0.29", deprecation_message)
E:\AI_Advantage\Data\Packages\Shirt_Swapper\venv\lib\site-packages\diffusers\models\unet_2d_blocks.py:294: FutureWarning: `SkipDownBlock2D` is deprecated and will be removed in version 0.29. Importing `SkipDownBlock2D` from `diffusers.models.unet_2d_blocks` is deprecated and this will be removed in a future version. Please use `from diffusers.models.unets.unet_2d_blocks import SkipDownBlock2D`, instead.
  deprecate("SkipDownBlock2D", "0.29", deprecation_message)
E:\AI_Advantage\Data\Packages\Shirt_Swapper\venv\lib\site-packages\diffusers\models\unet_2d_blocks.py:299: FutureWarning: `ResnetDownsampleBlock2D` is deprecated and will be removed in version 0.29. Importing `ResnetDownsampleBlock2D` from `diffusers.models.unet_2d_blocks` is deprecated and this will be removed in a future version. Please use `from diffusers.models.unets.unet_2d_blocks import ResnetDownsampleBlock2D`, instead.
  deprecate("ResnetDownsampleBlock2D", "0.29", deprecation_message)
E:\AI_Advantage\Data\Packages\Shirt_Swapper\venv\lib\site-packages\diffusers\models\unet_2d_blocks.py:304: FutureWarning: `SimpleCrossAttnDownBlock2D` is deprecated and will be removed in version 0.29. Importing `SimpleCrossAttnDownBlock2D` from `diffusers.models.unet_2d_blocks` is deprecated and this will be removed in a future version. Please use `from diffusers.models.unets.unet_2d_blocks import SimpleCrossAttnDownBlock2D`, instead.
  deprecate("SimpleCrossAttnDownBlock2D", "0.29", deprecation_message)
E:\AI_Advantage\Data\Packages\Shirt_Swapper\venv\lib\site-packages\diffusers\models\unet_2d_blocks.py:309: FutureWarning: `KDownBlock2D` is deprecated and will be removed in version 0.29. Importing `KDownBlock2D` from `diffusers.models.unet_2d_blocks` is deprecated and this will be removed in a future version. Please use `from diffusers.models.unets.unet_2d_blocks import KDownBlock2D`, instead.
  deprecate("KDownBlock2D", "0.29", deprecation_message)
E:\AI_Advantage\Data\Packages\Shirt_Swapper\venv\lib\site-packages\diffusers\models\unet_2d_blocks.py:314: FutureWarning: `KCrossAttnDownBlock2D` is deprecated and will be removed in version 0.29. Importing `KCrossAttnDownBlock2D` from `diffusers.models.unet_2d_blocks` is deprecated and this will be removed in a future version. Please use `from diffusers.models.unets.unet_2d_blocks import KCrossAttnDownBlock2D`, instead.
  deprecate("KCrossAttnDownBlock2D", "0.29", deprecation_message)
E:\AI_Advantage\Data\Packages\Shirt_Swapper\venv\lib\site-packages\diffusers\models\unet_2d_blocks.py:319: FutureWarning: `AttnUpBlock2D` is deprecated and will be removed in version 0.29. Importing `AttnUpBlock2D` from `diffusers.models.unet_2d_blocks` is deprecated and this will be removed in a future version. Please use `from diffusers.models.unets.unet_2d_blocks import AttnUpBlock2D`, instead.
  deprecate("AttnUpBlock2D", "0.29", deprecation_message)
E:\AI_Advantage\Data\Packages\Shirt_Swapper\venv\lib\site-packages\diffusers\models\unet_2d_blocks.py:324: FutureWarning: `CrossAttnUpBlock2D` is deprecated and will be removed in version 0.29. Importing `CrossAttnUpBlock2D` from `diffusers.models.unet_2d_blocks` is deprecated and this will be removed in a future version. Please use `from diffusers.models.unets.unet_2d_blocks import CrossAttnUpBlock2D`, instead.
  deprecate("CrossAttnUpBlock2D", "0.29", deprecation_message)
E:\AI_Advantage\Data\Packages\Shirt_Swapper\venv\lib\site-packages\diffusers\models\unet_2d_blocks.py:329: FutureWarning: `UpBlock2D` is deprecated and will be removed in version 0.29. Importing `UpBlock2D` from `diffusers.models.unet_2d_blocks` is deprecated and this will be removed in a future version. Please use `from diffusers.models.unets.unet_2d_blocks import UpBlock2D`, instead.
  deprecate("UpBlock2D", "0.29", deprecation_message)
E:\AI_Advantage\Data\Packages\Shirt_Swapper\venv\lib\site-packages\diffusers\models\unet_2d_blocks.py:334: FutureWarning: `UpDecoderBlock2D` is deprecated and will be removed in version 0.29. Importing `UpDecoderBlock2D` from `diffusers.models.unet_2d_blocks` is deprecated and this will be removed in a future version. Please use `from diffusers.models.unets.unet_2d_blocks import UpDecoderBlock2D`, instead.
  deprecate("UpDecoderBlock2D", "0.29", deprecation_message)
E:\AI_Advantage\Data\Packages\Shirt_Swapper\venv\lib\site-packages\diffusers\models\unet_2d_blocks.py:339: FutureWarning: `AttnUpDecoderBlock2D` is deprecated and will be removed in version 0.29. Importing `AttnUpDecoderBlock2D` from `diffusers.models.unet_2d_blocks` is deprecated and this will be removed in a future version. Please use `from diffusers.models.unets.unet_2d_blocks import AttnUpDecoderBlock2D`, instead.
  deprecate("AttnUpDecoderBlock2D", "0.29", deprecation_message)
E:\AI_Advantage\Data\Packages\Shirt_Swapper\venv\lib\site-packages\diffusers\models\unet_2d_blocks.py:344: FutureWarning: `AttnSkipUpBlock2D` is deprecated and will be removed in version 0.29. Importing `AttnSkipUpBlock2D` from `diffusers.models.unet_2d_blocks` is deprecated and this will be removed in a future version. Please use `from diffusers.models.unets.unet_2d_blocks import AttnSkipUpBlock2D`, instead.
  deprecate("AttnSkipUpBlock2D", "0.29", deprecation_message)
E:\AI_Advantage\Data\Packages\Shirt_Swapper\venv\lib\site-packages\diffusers\models\unet_2d_blocks.py:349: FutureWarning: `SkipUpBlock2D` is deprecated and will be removed in version 0.29. Importing `SkipUpBlock2D` from `diffusers.models.unet_2d_blocks` is deprecated and this will be removed in a future version. Please use `from diffusers.models.unets.unet_2d_blocks import SkipUpBlock2D`, instead.
  deprecate("SkipUpBlock2D", "0.29", deprecation_message)
E:\AI_Advantage\Data\Packages\Shirt_Swapper\venv\lib\site-packages\diffusers\models\unet_2d_blocks.py:354: FutureWarning: `ResnetUpsampleBlock2D` is deprecated and will be removed in version 0.29. Importing `ResnetUpsampleBlock2D` from `diffusers.models.unet_2d_blocks` is deprecated and this will be removed in a future version. Please use `from diffusers.models.unets.unet_2d_blocks import ResnetUpsampleBlock2D`, instead.
  deprecate("ResnetUpsampleBlock2D", "0.29", deprecation_message)
E:\AI_Advantage\Data\Packages\Shirt_Swapper\venv\lib\site-packages\diffusers\models\unet_2d_blocks.py:359: FutureWarning: `SimpleCrossAttnUpBlock2D` is deprecated and will be removed in version 0.29. Importing `SimpleCrossAttnUpBlock2D` from `diffusers.models.unet_2d_blocks` is deprecated and this will be removed in a future version. Please use `from diffusers.models.unets.unet_2d_blocks import SimpleCrossAttnUpBlock2D`, instead.
  deprecate("SimpleCrossAttnUpBlock2D", "0.29", deprecation_message)
E:\AI_Advantage\Data\Packages\Shirt_Swapper\venv\lib\site-packages\diffusers\models\unet_2d_blocks.py:364: FutureWarning: `KUpBlock2D` is deprecated and will be removed in version 0.29. Importing `KUpBlock2D` from `diffusers.models.unet_2d_blocks` is deprecated and this will be removed in a future version. Please use `from diffusers.models.unets.unet_2d_blocks import KUpBlock2D`, instead.
  deprecate("KUpBlock2D", "0.29", deprecation_message)
E:\AI_Advantage\Data\Packages\Shirt_Swapper\venv\lib\site-packages\diffusers\models\unet_2d_blocks.py:369: FutureWarning: `KCrossAttnUpBlock2D` is deprecated and will be removed in version 0.29. Importing `KCrossAttnUpBlock2D` from `diffusers.models.unet_2d_blocks` is deprecated and this will be removed in a future version. Please use `from diffusers.models.unets.unet_2d_blocks import KCrossAttnUpBlock2D`, instead.
  deprecate("KCrossAttnUpBlock2D", "0.29", deprecation_message)
E:\AI_Advantage\Data\Packages\Shirt_Swapper\venv\lib\site-packages\diffusers\models\unet_2d_blocks.py:375: FutureWarning: `KAttentionBlock` is deprecated and will be removed in version 0.29. Importing `KAttentionBlock` from `diffusers.models.unet_2d_blocks` is deprecated and this will be removed in a future version. Please use `from diffusers.models.unets.unet_2d_blocks import KAttentionBlock`, instead.
  deprecate("KAttentionBlock", "0.29", deprecation_message)

[rgthree] Loaded 37 epic nodes.
[rgthree] Will use rgthree's optimized recursive execution.

WAS Node Suite: OpenCV Python FFMPEG support is enabled
WAS Node Suite Warning: `ffmpeg_bin_path` is not set in `E:\AI_Advantage\Data\Packages\Shirt_Swapper\custom_nodes\was-node-suite-comfyui\was_suite_config.json` config file. Will attempt to use system ffmpeg binaries if available.
WAS Node Suite: Finished. Loaded 211 nodes successfully.

	"Be the change that you wish to see in the world." - Mahatma Gandhi

Import times for custom nodes:
   0.0 seconds: E:\AI_Advantage\Data\Packages\Shirt_Swapper\custom_nodes\websocket_image_save.py
   0.0 seconds: E:\AI_Advantage\Data\Packages\Shirt_Swapper\custom_nodes\image-resize-comfyui
   0.0 seconds: E:\AI_Advantage\Data\Packages\Shirt_Swapper\custom_nodes\cozy-sal-vton
   0.0 seconds: E:\AI_Advantage\Data\Packages\Shirt_Swapper\custom_nodes\ComfyUI_IPAdapter_plus
   0.0 seconds: E:\AI_Advantage\Data\Packages\Shirt_Swapper\custom_nodes\rgthree-comfy
   0.0 seconds: E:\AI_Advantage\Data\Packages\Shirt_Swapper\custom_nodes\ComfyUI_essentials
   0.1 seconds: E:\AI_Advantage\Data\Packages\Shirt_Swapper\custom_nodes\ComfyUI-Manager
   0.5 seconds: E:\AI_Advantage\Data\Packages\Shirt_Swapper\custom_nodes\ComfyUI-Impact-Pack
   0.9 seconds: E:\AI_Advantage\Data\Packages\Shirt_Swapper\custom_nodes\was-node-suite-comfyui
   1.6 seconds: E:\AI_Advantage\Data\Packages\Shirt_Swapper\custom_nodes\LCM_Inpaint-Outpaint_Comfy
   5.4 seconds (IMPORT FAILED): E:\AI_Advantage\Data\Packages\Shirt_Swapper\custom_nodes\human-parser-comfyui-node

Starting server

To see the GUI go to: http://127.0.0.1:8188
FETCH DATA from: E:\AI_Advantage\Data\Packages\Shirt_Swapper\custom_nodes\ComfyUI-Manager\extension-node-map.json

**Comment by gabidobo** [comment]
Hi @HydraBucket !

Looks like you don't have `ninja` installed, or it's not in the OS path: ` Command '['ninja', '-v']' returned non-zero exit status 1.`

The troubleshooting notes on ninja might help: https://github.com/cozymantis/human-parser-comfyui-node?tab=readme-ov-file#ninja-is-required-to-load-c-extensions

**Comment by HydraBucket** [comment]
unfortunately this didnt work, Ninja is installed within the OS path " C:\Users\Finn\AppData\Local\Programs\Python\Python310\Scripts" ... Any other clues? I'm keen to get this node going

**Comment by gabidobo** [comment]
This might be an issue with having multiple Pyton versions locally => Comfy's Python (located at `E:\AI_Advantage\Data\Packages\Shirt_Swapper\venv\Scripts\python.exe`) cannot see the Ninja installed under the global Python version (at `C:\Users\Finn\AppData\Local\Programs\Python\Python310`)
