### ISSUE TITLE
Fails to import node 

### ISSUE THREAD

**Issue by MrSmith44** [cozymantis/human-parser-comfyui-node#15]
File "C:\Users\Smith\Desktop\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\utils\cpp_extension.py", line 2100, in _run_ninja_build
    subprocess.run(
  File "subprocess.py", line 571, in run
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Smith\Desktop\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1879, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Smith\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\human-parser-comfyui-node\__init__.py", line 1, in <module>
    from .HumanParserLIPCustomNode import HumanParserLIPCustomNode
  File "C:\Users\Smith\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\human-parser-comfyui-node\HumanParserLIPCustomNode.py", line 5, in <module>
    from .utils import generate
  File "C:\Users\Smith\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\human-parser-comfyui-node\utils.py", line 8, in <module>
    from .schp import networks
  File "C:\Users\Smith\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\human-parser-comfyui-node\schp\networks\__init__.py", line 3, in <module>
    from .AugmentCE2P import resnet101
  File "C:\Users\Smith\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\human-parser-comfyui-node\schp\networks\AugmentCE2P.py", line 21, in <module>
    from ..modules import InPlaceABNSync
  File "C:\Users\Smith\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\human-parser-comfyui-node\schp\modules\__init__.py", line 1, in <module>
    from .bn import ABN, InPlaceABN, InPlaceABNSync
  File "C:\Users\Smith\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\human-parser-comfyui-node\schp\modules\bn.py", line 10, in <module>
    from .functions import *
  File "C:\Users\Smith\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\human-parser-comfyui-node\schp\modules\functions.py", line 12, in <module>
    _backend = load(name="inplace_abn",
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Smith\Desktop\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\utils\cpp_extension.py", line 1308, in load
    return _jit_compile(
           ^^^^^^^^^^^^^
  File "C:\Users\Smith\Desktop\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\utils\cpp_extension.py", line 1710, in _jit_compile
    _write_ninja_file_and_build_library(
  File "C:\Users\Smith\Desktop\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\utils\cpp_extension.py", line 1823, in _write_ninja_file_and_build_library
    _run_ninja_build(
  File "C:\Users\Smith\Desktop\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\utils\cpp_extension.py", line 2116, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error building extension 'inplace_abn': [1/2] cl /showIncludes -DTORCH_EXTENSION_NAME=inplace_abn -DTORCH_API_INCLUDE_EXTENSION_H -IC:\Users\Smith\Desktop\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\include -IC:\Users\Smith\Desktop\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\include\torch\csrc\api\include -IC:\Users\Smith\Desktop\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\include\TH -IC:\Users\Smith\Desktop\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.5\include" -IC:\Users\Smith\Desktop\ComfyUI_windows_portable\python_embeded\Include -D_GLIBCXX_USE_CXX11_ABI=0 /MD /wd4819 /wd4251 /wd4244 /wd4267 /wd4275 /wd4018 /wd4190 /wd4624 /wd4067 /wd4068 /EHsc /std:c++17 -O3 -c C:\Users\Smith\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\human-parser-comfyui-node\schp\modules\src\inplace_abn.cpp /Foinplace_abn.o
FAILED: inplace_abn.o
cl /showIncludes -DTORCH_EXTENSION_NAME=inplace_abn -DTORCH_API_INCLUDE_EXTENSION_H -IC:\Users\Smith\Desktop\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\include -IC:\Users\Smith\Desktop\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\include\torch\csrc\api\include -IC:\Users\Smith\Desktop\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\include\TH -IC:\Users\Smith\Desktop\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.5\include" -IC:\Users\Smith\Desktop\ComfyUI_windows_portable\python_embeded\Include -D_GLIBCXX_USE_CXX11_ABI=0 /MD /wd4819 /wd4251 /wd4244 /wd4267 /wd4275 /wd4018 /wd4190 /wd4624 /wd4067 /wd4068 /EHsc /std:c++17 -O3 -c C:\Users\Smith\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\human-parser-comfyui-node\schp\modules\src\inplace_abn.cpp /Foinplace_abn.o
Microsoft (R) C/C++ Optimizing Compiler Version 19.40.33811 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

cl : Command line warning D9002 : ignoring unknown option '-O3'
C:\Users\Smith\Desktop\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\include\torch/csrc/python_headers.h(12): fatal error C1083: Cannot open include file: 'Python.h': No such file or directory
ninja: build stopped: subcommand failed.

Cannot import C:\Users\Smith\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\human-parser-comfyui-node module for custom nodes: Error building extension 'inplace_abn': [1/2] cl /showIncludes -DTORCH_EXTENSION_NAME=inplace_abn -DTORCH_API_INCLUDE_EXTENSION_H -IC:\Users\Smith\Desktop\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\include -IC:\Users\Smith\Desktop\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\include\torch\csrc\api\include -IC:\Users\Smith\Desktop\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\include\TH -IC:\Users\Smith\Desktop\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.5\include" -IC:\Users\Smith\Desktop\ComfyUI_windows_portable\python_embeded\Include -D_GLIBCXX_USE_CXX11_ABI=0 /MD /wd4819 /wd4251 /wd4244 /wd4267 /wd4275 /wd4018 /wd4190 /wd4624 /wd4067 /wd4068 /EHsc /std:c++17 -O3 -c C:\Users\Smith\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\human-parser-comfyui-node\schp\modules\src\inplace_abn.cpp /Foinplace_abn.o
FAILED: inplace_abn.o
cl /showIncludes -DTORCH_EXTENSION_NAME=inplace_abn -DTORCH_API_INCLUDE_EXTENSION_H -IC:\Users\Smith\Desktop\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\include -IC:\Users\Smith\Desktop\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\include\torch\csrc\api\include -IC:\Users\Smith\Desktop\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\include\TH -IC:\Users\Smith\Desktop\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.5\include" -IC:\Users\Smith\Desktop\ComfyUI_windows_portable\python_embeded\Include -D_GLIBCXX_USE_CXX11_ABI=0 /MD /wd4819 /wd4251 /wd4244 /wd4267 /wd4275 /wd4018 /wd4190 /wd4624 /wd4067 /wd4068 /EHsc /std:c++17 -O3 -c C:\Users\Smith\Desktop\ComfyUI_windows_portable\ComfyUI\custom_nodes\human-parser-comfyui-node\schp\modules\src\inplace_abn.cpp /Foinplace_abn.o
Microsoft (R) C/C++ Optimizing Compiler Version 19.40.33811 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

cl : Command line warning D9002 : ignoring unknown option '-O3'
C:\Users\Smith\Desktop\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\include\torch/csrc/python_headers.h(12): fatal error C1083: Cannot open include file: 'Python.h': No such file or directory
ninja: build stopped: subcommand failed.

**Comment by Hituh** [comment]
Hi there, did you figure anything about this issue? Been stuck on it for hours.

**Comment by MrSmith44** [comment]
I’ve avoided this node and the headache for weeks mate I might have another
look tonight and see if I can make any sense of it if I work anything out
I’ll let you know 👍🏽
