### ISSUE TITLE
subprocess.CalledProcessError: Command '['where', 'cl']' returned non-zero exit status 1

### ISSUE THREAD

**Issue by NeoLoger** [cozymantis/human-parser-comfyui-node#16]
When I try to load the node I get an error, I didn't mange to find a solution.

The error I get is `subprocess.CalledProcessError: Command '['where', 'cl']' returned non-zero exit status 1.`
```
INFO: Could not find files for the given pattern(s).
Traceback (most recent call last):
  File "A:\ComfyUI\ComfyUI\nodes.py", line 1893, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "A:\ComfyUI\ComfyUI\custom_nodes\human-parser-comfyui-node\__init__.py", line 1, in <module>
    from .HumanParserLIPCustomNode import HumanParserLIPCustomNode
  File "A:\ComfyUI\ComfyUI\custom_nodes\human-parser-comfyui-node\HumanParserLIPCustomNode.py", line 5, in <module>
    from .utils import generate
  File "A:\ComfyUI\ComfyUI\custom_nodes\human-parser-comfyui-node\utils.py", line 8, in <module>
    from .schp import networks
  File "A:\ComfyUI\ComfyUI\custom_nodes\human-parser-comfyui-node\schp\networks\__init__.py", line 3, in <module>
    from .AugmentCE2P import resnet101
  File "A:\ComfyUI\ComfyUI\custom_nodes\human-parser-comfyui-node\schp\networks\AugmentCE2P.py", line 21, in <module>
    from ..modules import InPlaceABNSync
  File "A:\ComfyUI\ComfyUI\custom_nodes\human-parser-comfyui-node\schp\modules\__init__.py", line 1, in <module>
    from .bn import ABN, InPlaceABN, InPlaceABNSync
  File "A:\ComfyUI\ComfyUI\custom_nodes\human-parser-comfyui-node\schp\modules\bn.py", line 10, in <module>
    from .functions import *
  File "A:\ComfyUI\ComfyUI\custom_nodes\human-parser-comfyui-node\schp\modules\functions.py", line 12, in <module>
    _backend = load(name="inplace_abn",
  File "A:\ComfyUI\python_embeded\lib\site-packages\torch\utils\cpp_extension.py", line 1309, in load
    return _jit_compile(
  File "A:\ComfyUI\python_embeded\lib\site-packages\torch\utils\cpp_extension.py", line 1719, in _jit_compile
    _write_ninja_file_and_build_library(
  File "A:\ComfyUI\python_embeded\lib\site-packages\torch\utils\cpp_extension.py", line 1819, in _write_ninja_file_and_build_library
    _write_ninja_file_to_build_library(
  File "A:\ComfyUI\python_embeded\lib\site-packages\torch\utils\cpp_extension.py", line 2249, in _write_ninja_file_to_build_library
    _write_ninja_file(
  File "A:\ComfyUI\python_embeded\lib\site-packages\torch\utils\cpp_extension.py", line 2385, in _write_ninja_file
    cl_paths = subprocess.check_output(['where',
  File "subprocess.py", line 421, in check_output
  File "subprocess.py", line 526, in run
subprocess.CalledProcessError: Command '['where', 'cl']' returned non-zero exit status 1.

Cannot import A:\ComfyUI\ComfyUI\custom_nodes\human-parser-comfyui-node module for custom nodes: Command '['where', 'cl']' returned non-zero exit status 1.
```

Before I was getting `CUDA_HOME environment variable is not set. Please set it to your CUDA install root`

So I installed the [CUDA Toolkit 12.5](https://developer.nvidia.com/cuda-downloads?target_os=Windows&target_arch=x86_64&target_version=11&target_type=exe_local) from Nvidia and now I'm stuck with this error.

I would appreciate any assistance. 

Its the only node I have issues with.
```
Import times for custom nodes:
   0.0 seconds: A:\ComfyUI\ComfyUI\custom_nodes\rembg-comfyui-node-better
   0.0 seconds: A:\ComfyUI\ComfyUI\custom_nodes\websocket_image_save.py
   0.0 seconds: A:\ComfyUI\ComfyUI\custom_nodes\pose-generator-comfyui-node
   0.0 seconds: A:\ComfyUI\ComfyUI\custom_nodes\masquerade-nodes-comfyui
   0.0 seconds: A:\ComfyUI\ComfyUI\custom_nodes\ComfyUI_InstantID
   0.0 seconds: A:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-SDXL-EmptyLatentImage
   0.0 seconds: A:\ComfyUI\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
   0.0 seconds: A:\ComfyUI\ComfyUI\custom_nodes\comfyui-mask-boundingbox
   0.0 seconds: A:\ComfyUI\ComfyUI\custom_nodes\comfyui-inpaint-nodes
   0.0 seconds: A:\ComfyUI\ComfyUI\custom_nodes\ComfyMath
   0.0 seconds: A:\ComfyUI\ComfyUI\custom_nodes\DZ-FaceDetailer
   0.0 seconds: A:\ComfyUI\ComfyUI\custom_nodes\Derfuu_ComfyUI_ModdedNodes
   0.0 seconds: A:\ComfyUI\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
   0.0 seconds: A:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-WD14-Tagger
   0.0 seconds: A:\ComfyUI\ComfyUI\custom_nodes\rgthree-comfy
   0.0 seconds: A:\ComfyUI\ComfyUI\custom_nodes\ComfyUI_essentials
   0.0 seconds: A:\ComfyUI\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes
   0.0 seconds: A:\ComfyUI\ComfyUI\custom_nodes\comfyui_controlnet_aux
   0.0 seconds: A:\ComfyUI\ComfyUI\custom_nodes\ComfyUI_tinyterraNodes
   0.2 seconds: A:\ComfyUI\ComfyUI\custom_nodes\ComfyUI_TensorRT
   0.2 seconds: A:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager
   0.4 seconds: A:\ComfyUI\ComfyUI\custom_nodes\clipseg.py
   0.4 seconds (IMPORT FAILED): A:\ComfyUI\ComfyUI\custom_nodes\human-parser-comfyui-node
   0.6 seconds: A:\ComfyUI\ComfyUI\custom_nodes\ComfyUI_FaceAnalysis
   0.7 seconds: A:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
   0.7 seconds: A:\ComfyUI\ComfyUI\custom_nodes\rembg-comfyui-node
   0.7 seconds: A:\ComfyUI\ComfyUI\custom_nodes\was-node-suite-comfyui
   1.7 seconds: A:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-YoloWorld-EfficientSAM
```

**Comment by NeoLoger** [comment]
Ok had some progress, I missed the 'where', 'cl' issue part on the main page but now I get a different error..

Its becoming way to pain in the ass to run.

```
Traceback (most recent call last):
  File "A:\ComfyUI\python_embeded\lib\site-packages\torch\utils\cpp_extension.py", line 2107, in _run_ninja_build
    subprocess.run(
  File "subprocess.py", line 526, in run
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "A:\ComfyUI\ComfyUI\nodes.py", line 1893, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "A:\ComfyUI\ComfyUI\custom_nodes\human-parser-comfyui-node\__init__.py", line 1, in <module>
    from .HumanParserLIPCustomNode import HumanParserLIPCustomNode
  File "A:\ComfyUI\ComfyUI\custom_nodes\human-parser-comfyui-node\HumanParserLIPCustomNode.py", line 5, in <module>
    from .utils import generate
  File "A:\ComfyUI\ComfyUI\custom_nodes\human-parser-comfyui-node\utils.py", line 8, in <module>
    from .schp import networks
  File "A:\ComfyUI\ComfyUI\custom_nodes\human-parser-comfyui-node\schp\networks\__init__.py", line 3, in <module>
    from .AugmentCE2P import resnet101
  File "A:\ComfyUI\ComfyUI\custom_nodes\human-parser-comfyui-node\schp\networks\AugmentCE2P.py", line 21, in <module>
    from ..modules import InPlaceABNSync
  File "A:\ComfyUI\ComfyUI\custom_nodes\human-parser-comfyui-node\schp\modules\__init__.py", line 1, in <module>
    from .bn import ABN, InPlaceABN, InPlaceABNSync
  File "A:\ComfyUI\ComfyUI\custom_nodes\human-parser-comfyui-node\schp\modules\bn.py", line 10, in <module>
    from .functions import *
  File "A:\ComfyUI\ComfyUI\custom_nodes\human-parser-comfyui-node\schp\modules\functions.py", line 12, in <module>
    _backend = load(name="inplace_abn",
  File "A:\ComfyUI\python_embeded\lib\site-packages\torch\utils\cpp_extension.py", line 1309, in load
    return _jit_compile(
  File "A:\ComfyUI\python_embeded\lib\site-packages\torch\utils\cpp_extension.py", line 1719, in _jit_compile
    _write_ninja_file_and_build_library(
  File "A:\ComfyUI\python_embeded\lib\site-packages\torch\utils\cpp_extension.py", line 1832, in _write_ninja_file_and_build_library
    _run_ninja_build(
  File "A:\ComfyUI\python_embeded\lib\site-packages\torch\utils\cpp_extension.py", line 2123, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error building extension 'inplace_abn': [1/5] cl /showIncludes -DTORCH_EXTENSION_NAME=inplace_abn -DTORCH_API_INCLUDE_EXTENSION_H -IA:\ComfyUI\python_embeded\lib\site-packages\torch\include -IA:\ComfyUI\python_embeded\lib\site-packages\torch\include\torch\csrc\api\include -IA:\ComfyUI\python_embeded\lib\site-packages\torch\include\TH -IA:\ComfyUI\python_embeded\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.5\include" -IA:\ComfyUI\python_embeded\Include -D_GLIBCXX_USE_CXX11_ABI=0 /MD /wd4819 /wd4251 /wd4244 /wd4267 /wd4275 /wd4018 /wd4190 /wd4624 /wd4067 /wd4068 /EHsc /std:c++17 -O3 -c A:\ComfyUI\ComfyUI\custom_nodes\human-parser-comfyui-node\schp\modules\src\inplace_abn_cpu.cpp /Foinplace_abn_cpu.o
Microsoft (R) C/C++ Optimizing Compiler Version 19.40.33811 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

cl : Command line warning D9002 : ignoring unknown option '-O3'
[2/5] cl /showIncludes -DTORCH_EXTENSION_NAME=inplace_abn -DTORCH_API_INCLUDE_EXTENSION_H -IA:\ComfyUI\python_embeded\lib\site-packages\torch\include -IA:\ComfyUI\python_embeded\lib\site-packages\torch\include\torch\csrc\api\include -IA:\ComfyUI\python_embeded\lib\site-packages\torch\include\TH -IA:\ComfyUI\python_embeded\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.5\include" -IA:\ComfyUI\python_embeded\Include -D_GLIBCXX_USE_CXX11_ABI=0 /MD /wd4819 /wd4251 /wd4244 /wd4267 /wd4275 /wd4018 /wd4190 /wd4624 /wd4067 /wd4068 /EHsc /std:c++17 -O3 -c A:\ComfyUI\ComfyUI\custom_nodes\human-parser-comfyui-node\schp\modules\src\inplace_abn.cpp /Foinplace_abn.o
FAILED: inplace_abn.o
cl /showIncludes -DTORCH_EXTENSION_NAME=inplace_abn -DTORCH_API_INCLUDE_EXTENSION_H -IA:\ComfyUI\python_embeded\lib\site-packages\torch\include -IA:\ComfyUI\python_embeded\lib\site-packages\torch\include\torch\csrc\api\include -IA:\ComfyUI\python_embeded\lib\site-packages\torch\include\TH -IA:\ComfyUI\python_embeded\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.5\include" -IA:\ComfyUI\python_embeded\Include -D_GLIBCXX_USE_CXX11_ABI=0 /MD /wd4819 /wd4251 /wd4244 /wd4267 /wd4275 /wd4018 /wd4190 /wd4624 /wd4067 /wd4068 /EHsc /std:c++17 -O3 -c A:\ComfyUI\ComfyUI\custom_nodes\human-parser-comfyui-node\schp\modules\src\inplace_abn.cpp /Foinplace_abn.o
Microsoft (R) C/C++ Optimizing Compiler Version 19.40.33811 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

cl : Command line warning D9002 : ignoring unknown option '-O3'
A:\ComfyUI\python_embeded\lib\site-packages\torch\include\torch/csrc/python_headers.h(12): fatal error C1083: Cannot open include file: 'Python.h': No such file or directory
[3/5] C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.5\bin\nvcc --generate-dependencies-with-compile --dependency-output inplace_abn_cuda_half.cuda.o.d -Xcudafe --diag_suppress=dll_interface_conflict_dllexport_assumed -Xcudafe --diag_suppress=dll_interface_conflict_none_assumed -Xcudafe --diag_suppress=field_without_dll_interface -Xcudafe --diag_suppress=base_class_has_different_dll_interface -Xcompiler /EHsc -Xcompiler /wd4068 -Xcompiler /wd4067 -Xcompiler /wd4624 -Xcompiler /wd4190 -Xcompiler /wd4018 -Xcompiler /wd4275 -Xcompiler /wd4267 -Xcompiler /wd4244 -Xcompiler /wd4251 -Xcompiler /wd4819 -Xcompiler /MD -DTORCH_EXTENSION_NAME=inplace_abn -DTORCH_API_INCLUDE_EXTENSION_H -IA:\ComfyUI\python_embeded\lib\site-packages\torch\include -IA:\ComfyUI\python_embeded\lib\site-packages\torch\include\torch\csrc\api\include -IA:\ComfyUI\python_embeded\lib\site-packages\torch\include\TH -IA:\ComfyUI\python_embeded\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.5\include" -IA:\ComfyUI\python_embeded\Include -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 -std=c++17 --expt-extended-lambda -c A:\ComfyUI\ComfyUI\custom_nodes\human-parser-comfyui-node\schp\modules\src\inplace_abn_cuda_half.cu -o inplace_abn_cuda_half.cuda.o
inplace_abn_cuda_half.cu
tmpxft_00006b64_00000000-10_inplace_abn_cuda_half.cudafe1.cpp
[4/5] C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.5\bin\nvcc --generate-dependencies-with-compile --dependency-output inplace_abn_cuda.cuda.o.d -Xcudafe --diag_suppress=dll_interface_conflict_dllexport_assumed -Xcudafe --diag_suppress=dll_interface_conflict_none_assumed -Xcudafe --diag_suppress=field_without_dll_interface -Xcudafe --diag_suppress=base_class_has_different_dll_interface -Xcompiler /EHsc -Xcompiler /wd4068 -Xcompiler /wd4067 -Xcompiler /wd4624 -Xcompiler /wd4190 -Xcompiler /wd4018 -Xcompiler /wd4275 -Xcompiler /wd4267 -Xcompiler /wd4244 -Xcompiler /wd4251 -Xcompiler /wd4819 -Xcompiler /MD -DTORCH_EXTENSION_NAME=inplace_abn -DTORCH_API_INCLUDE_EXTENSION_H -IA:\ComfyUI\python_embeded\lib\site-packages\torch\include -IA:\ComfyUI\python_embeded\lib\site-packages\torch\include\torch\csrc\api\include -IA:\ComfyUI\python_embeded\lib\site-packages\torch\include\TH -IA:\ComfyUI\python_embeded\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.5\include" -IA:\ComfyUI\python_embeded\Include -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 -std=c++17 --expt-extended-lambda -c A:\ComfyUI\ComfyUI\custom_nodes\human-parser-comfyui-node\schp\modules\src\inplace_abn_cuda.cu -o inplace_abn_cuda.cuda.o
inplace_abn_cuda.cu
tmpxft_00005794_00000000-10_inplace_abn_cuda.cudafe1.cpp
ninja: build stopped: subcommand failed.


Cannot import A:\ComfyUI\ComfyUI\custom_nodes\human-parser-comfyui-node module for custom nodes: Error building extension 'inplace_abn': [1/5] cl /showIncludes -DTORCH_EXTENSION_NAME=inplace_abn -DTORCH_API_INCLUDE_EXTENSION_H -IA:\ComfyUI\python_embeded\lib\site-packages\torch\include -IA:\ComfyUI\python_embeded\lib\site-packages\torch\include\torch\csrc\api\include -IA:\ComfyUI\python_embeded\lib\site-packages\torch\include\TH -IA:\ComfyUI\python_embeded\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.5\include" -IA:\ComfyUI\python_embeded\Include -D_GLIBCXX_USE_CXX11_ABI=0 /MD /wd4819 /wd4251 /wd4244 /wd4267 /wd4275 /wd4018 /wd4190 /wd4624 /wd4067 /wd4068 /EHsc /std:c++17 -O3 -c A:\ComfyUI\ComfyUI\custom_nodes\human-parser-comfyui-node\schp\modules\src\inplace_abn_cpu.cpp /Foinplace_abn_cpu.o
Microsoft (R) C/C++ Optimizing Compiler Version 19.40.33811 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

cl : Command line warning D9002 : ignoring unknown option '-O3'
[2/5] cl /showIncludes -DTORCH_EXTENSION_NAME=inplace_abn -DTORCH_API_INCLUDE_EXTENSION_H -IA:\ComfyUI\python_embeded\lib\site-packages\torch\include -IA:\ComfyUI\python_embeded\lib\site-packages\torch\include\torch\csrc\api\include -IA:\ComfyUI\python_embeded\lib\site-packages\torch\include\TH -IA:\ComfyUI\python_embeded\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.5\include" -IA:\ComfyUI\python_embeded\Include -D_GLIBCXX_USE_CXX11_ABI=0 /MD /wd4819 /wd4251 /wd4244 /wd4267 /wd4275 /wd4018 /wd4190 /wd4624 /wd4067 /wd4068 /EHsc /std:c++17 -O3 -c A:\ComfyUI\ComfyUI\custom_nodes\human-parser-comfyui-node\schp\modules\src\inplace_abn.cpp /Foinplace_abn.o
FAILED: inplace_abn.o
cl /showIncludes -DTORCH_EXTENSION_NAME=inplace_abn -DTORCH_API_INCLUDE_EXTENSION_H -IA:\ComfyUI\python_embeded\lib\site-packages\torch\include -IA:\ComfyUI\python_embeded\lib\site-packages\torch\include\torch\csrc\api\include -IA:\ComfyUI\python_embeded\lib\site-packages\torch\include\TH -IA:\ComfyUI\python_embeded\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.5\include" -IA:\ComfyUI\python_embeded\Include -D_GLIBCXX_USE_CXX11_ABI=0 /MD /wd4819 /wd4251 /wd4244 /wd4267 /wd4275 /wd4018 /wd4190 /wd4624 /wd4067 /wd4068 /EHsc /std:c++17 -O3 -c A:\ComfyUI\ComfyUI\custom_nodes\human-parser-comfyui-node\schp\modules\src\inplace_abn.cpp /Foinplace_abn.o
Microsoft (R) C/C++ Optimizing Compiler Version 19.40.33811 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

cl : Command line warning D9002 : ignoring unknown option '-O3'
A:\ComfyUI\python_embeded\lib\site-packages\torch\include\torch/csrc/python_headers.h(12): fatal error C1083: Cannot open include file: 'Python.h': No such file or directory
[3/5] C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.5\bin\nvcc --generate-dependencies-with-compile --dependency-output inplace_abn_cuda_half.cuda.o.d -Xcudafe --diag_suppress=dll_interface_conflict_dllexport_assumed -Xcudafe --diag_suppress=dll_interface_conflict_none_assumed -Xcudafe --diag_suppress=field_without_dll_interface -Xcudafe --diag_suppress=base_class_has_different_dll_interface -Xcompiler /EHsc -Xcompiler /wd4068 -Xcompiler /wd4067 -Xcompiler /wd4624 -Xcompiler /wd4190 -Xcompiler /wd4018 -Xcompiler /wd4275 -Xcompiler /wd4267 -Xcompiler /wd4244 -Xcompiler /wd4251 -Xcompiler /wd4819 -Xcompiler /MD -DTORCH_EXTENSION_NAME=inplace_abn -DTORCH_API_INCLUDE_EXTENSION_H -IA:\ComfyUI\python_embeded\lib\site-packages\torch\include -IA:\ComfyUI\python_embeded\lib\site-packages\torch\include\torch\csrc\api\include -IA:\ComfyUI\python_embeded\lib\site-packages\torch\include\TH -IA:\ComfyUI\python_embeded\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.5\include" -IA:\ComfyUI\python_embeded\Include -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 -std=c++17 --expt-extended-lambda -c A:\ComfyUI\ComfyUI\custom_nodes\human-parser-comfyui-node\schp\modules\src\inplace_abn_cuda_half.cu -o inplace_abn_cuda_half.cuda.o
inplace_abn_cuda_half.cu
tmpxft_00006b64_00000000-10_inplace_abn_cuda_half.cudafe1.cpp
[4/5] C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.5\bin\nvcc --generate-dependencies-with-compile --dependency-output inplace_abn_cuda.cuda.o.d -Xcudafe --diag_suppress=dll_interface_conflict_dllexport_assumed -Xcudafe --diag_suppress=dll_interface_conflict_none_assumed -Xcudafe --diag_suppress=field_without_dll_interface -Xcudafe --diag_suppress=base_class_has_different_dll_interface -Xcompiler /EHsc -Xcompiler /wd4068 -Xcompiler /wd4067 -Xcompiler /wd4624 -Xcompiler /wd4190 -Xcompiler /wd4018 -Xcompiler /wd4275 -Xcompiler /wd4267 -Xcompiler /wd4244 -Xcompiler /wd4251 -Xcompiler /wd4819 -Xcompiler /MD -DTORCH_EXTENSION_NAME=inplace_abn -DTORCH_API_INCLUDE_EXTENSION_H -IA:\ComfyUI\python_embeded\lib\site-packages\torch\include -IA:\ComfyUI\python_embeded\lib\site-packages\torch\include\torch\csrc\api\include -IA:\ComfyUI\python_embeded\lib\site-packages\torch\include\TH -IA:\ComfyUI\python_embeded\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.5\include" -IA:\ComfyUI\python_embeded\Include -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 -std=c++17 --expt-extended-lambda -c A:\ComfyUI\ComfyUI\custom_nodes\human-parser-comfyui-node\schp\modules\src\inplace_abn_cuda.cu -o inplace_abn_cuda.cuda.o
inplace_abn_cuda.cu
tmpxft_00005794_00000000-10_inplace_abn_cuda.cudafe1.cpp
ninja: build stopped: subcommand failed.
```

**Comment by gabidobo** [comment]
@NeoLoger I know, it's a bit tough to get this running on Windows, the env needs to be setup right.
We have a bunch of tips for Windows here, including links to older issues related to your issue: https://github.com/cozymantis/human-parser-comfyui-node?tab=readme-ov-file#windows-troubleshooting
