### ISSUE TITLE
  error: [WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by melanie0901** [cozymantis/human-parser-comfyui-node#21]
I got Torch 2.1.2 + Cuda 11.8
ninja set on the path

[Prompt Server] web root: E:\C\web
E:\C\.ext\Lib\site-packages\diffusers\utils\outputs.py:63: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  torch.utils._pytree._register_pytree_node(
E:\C\.ext\Lib\site-packages\diffusers\utils\outputs.py:63: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  torch.utils._pytree._register_pytree_node(
Traceback (most recent call last):
  File "E:\C\nodes.py", line 1941, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\C\custom_nodes\human-parser-comfyui-node\__init__.py", line 1, in <module>
    from .HumanParserLIPCustomNode import HumanParserLIPCustomNode
  File "E:\C\custom_nodes\human-parser-comfyui-node\HumanParserLIPCustomNode.py", line 5, in <module>
    from .utils import generate
  File "E:\C\custom_nodes\human-parser-comfyui-node\utils.py", line 8, in <module>
    from .schp import networks
  File "E:\C\custom_nodes\human-parser-comfyui-node\schp\networks\__init__.py", line 3, in <module>
    from .AugmentCE2P import resnet101
  File "E:\C\custom_nodes\human-parser-comfyui-node\schp\networks\AugmentCE2P.py", line 21, in <module>
    from ..modules import InPlaceABNSync
  File "E:\C\custom_nodes\human-parser-comfyui-node\schp\modules\__init__.py", line 1, in <module>
    from .bn import ABN, InPlaceABN, InPlaceABNSync
  File "E:\C\custom_nodes\human-parser-comfyui-node\schp\modules\bn.py", line 10, in <module>
    from .functions import *
  File "E:\C\custom_nodes\human-parser-comfyui-node\schp\modules\functions.py", line 13, in <module>
    _backend = load(name="inplace_abn",
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\C\.ext\Lib\site-packages\torch\utils\cpp_extension.py", line 1306, in load
    return _jit_compile(
           ^^^^^^^^^^^^^
  File "E:\C\.ext\Lib\site-packages\torch\utils\cpp_extension.py", line 1736, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\C\.ext\Lib\site-packages\torch\utils\cpp_extension.py", line 2132, in _import_module_from_library
    module = importlib.util.module_from_spec(spec)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: DLL load failed while importing inplace_abn: 找不到指定的模块。

Cannot import E:\C\custom_nodes\human-parser-comfyui-node module for custom nodes: DLL load failed while importing inplace_abn: 找不到指定的模块。

**Comment by memx200** [comment]
Yo my Friend
I was stuck for a while, but using WSL2 solved most of my issues. It's the easiest and best solution if you're on Windows.

https://followfox.ai/tpost/z0oej4ufk1-getting-started-with-comfyui-on-wsl2

You may not need to follow the guide exactly—adapt it based on your environment.

If you have any questions, feel free to reach out, and I'll help!

**Comment by melanie0901** [comment]
> 哟，我的朋友， 我被困了一段时间，但使用 WSL2 解决了我的大部分问题。如果你使用 Windows，这是最简单、最好的解决方案。
> 
> https://followfox.ai/tpost/z0oej4ufk1-getting-started-with-comfyui-on-wsl2
> 
> 您可能不需要完全遵循指南——根据您的环境进行调整。
> 
> 如果您有任何疑问，请随时联系我，我会提供帮助！

Thank you friend! I will try!
